### ISSUE TITLE
Tests are failing but GHA passes

### ISSUE THREAD

**Issue by Xiangs18** [kbaseapps/GenomeFileUtil#203]

**Comment by MrCreosote** [comment]
@Xiangs18 I think this can be closed as fixed right?

**Comment by Xiangs18** [comment]
right, same goes to https://github.com/kbaseapps/AssemblyUtil/issues/90

**Comment by MrCreosote** [comment]
Fixed in https://github.com/kbaseapps/GenomeFileUtil/pull/204
