### ISSUE TITLE
Token shouldn't be loaded from KB_AUTH_TOKEN system environment in Impl code.

### ISSUE THREAD

**Issue by rsutormin** [kbaseapps/GenomeFileUtil#52]
1) here:
https://github.com/kbaseapps/GenomeFileUtil/blob/53a3d8f744cfe1cb6675d7aa29b895c556457e40/lib/GenomeFileUtil/core/GenbankUploaderScript.py#L107

2) and here:
https://github.com/kbaseapps/GenomeFileUtil/blob/53a3d8f744cfe1cb6675d7aa29b895c556457e40/lib/GenomeFileUtil/core/GenomeToGenbank.py#L95

**Comment by JamesJeffryes** [comment]
now obsolete
