### ISSUE TITLE
Token should be explicitly passed to workspace client.

### ISSUE THREAD

**Issue by rsutormin** [kbaseapps/GenomeFileUtil#53]
In many places token is not passed (it's expected to be in some system env-variable)
For instance it happens here:
https://github.com/kbaseapps/GenomeFileUtil/blob/53a3d8f744cfe1cb6675d7aa29b895c556457e40/lib/GenomeFileUtil/core/GenbankUploaderScript.py#L114

And another example is here (there is workspace client creation inside assembly script, and again without token):
https://github.com/kbaseapps/GenomeFileUtil/blob/53a3d8f744cfe1cb6675d7aa29b895c556457e40/lib/GenomeFileUtil/core/GenbankUploaderScript.py#L1230

**Comment by JamesJeffryes** [comment]
obsolete
